./InferStudy -e ../databases/abalone/abalone -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/adult/adult -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/australian/australian -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/automobile/automobile -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/balance/balance -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/banana/banana -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/bands/bands -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/bupa/bupa -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/census/census -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/cleveland/cleveland -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/coil2000/coil2000 -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/connect-4/connect-4 -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/covtype_2_vs_1/covtype_2_vs_1 -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/crx/crx -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/fars_0_vs_4_/fars_0_vs_4_ -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/flare/flare -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/german/german -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/heart/heart -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/ionosphere/ionosphere -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/iris/iris -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/led7digit/led7digit -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/letter/letter -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/magic/magic -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/mammographic/mammographic -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/movement_libras/movement_libras -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/newthyroid/newthyroid -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/page-blocks/page-blocks -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/penbased/penbased -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/phoneme/phoneme -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/pima/pima -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/ring/ring -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/saheart/saheart -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/satimage/satimage -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/segment/segment -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/shuttle/shuttle -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/sonar/sonar -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/spambase/spambase -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/spectfheart/spectfheart -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/texture/texture -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/thyroid/thyroid -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/twonorm/twonorm -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/vehicle/vehicle -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/vowel/vowel -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/wine/wine -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/winequality-red/winequality-red -model 2 -nlabel 3 -maxrules 1024
./InferStudy -e ../databases/winequality-white/winequality-white -model 2 -nlabel 3 -maxrules 1024
#./InferStudy -e ../databases/kddcup_full_normalsus_DOS/kddcup_full_normalsus_DOS -model 2 -nlabel 3 -maxrules 1024
#./InferStudy -e ../databases/susy/susy -model 2 -nlabel 3 -maxrules 1024
#./InferStudy -e ../databases/higgs/higgs -model 2 -nlabel 3 -maxrules 1024 -PerCentOnTest 0.001
#./InferStudy -e ../databases/hepmassAll/hepmassAll -model 2 -nlabel 3 -maxrules 1024 -PerCentOnTest 0.001
